export const errorMessages = [
  // User Controller 100 till 129
  { code: 100, message: 'User created successfully' },
  { code: 101, message: 'Error hashing password' },
  { code: 102, message: 'Image is required' },
  { code: 103, message: 'Unauthorized Person' },
  { code: 104, message: 'User not found' },
  { code: 105, message: 'Password reset email sent' },
  { code: 106, message: 'Error sending email' },
  { code: 107, message: 'Password reset token is invalid or has expired' },
  { code: 113, message: 'Password has been reset successfully' },
  { code: 109, message: 'User not found by this id' },
  { code: 110, message: 'Validation error' },
  { code: 111, message: 'Access Denied' },
  { code: 112, message: 'Error in forgot password' },

  // Bank Account Controller 130 till 159
  { code: 130, message: 'Bank account created successfully' },
  { code: 140, message: 'Token not found' },
  { code: 141, message: 'Bank Account not found' },
  { code: 142, message: 'Bank accounts fetched successfully' },
  { code: 143, message: 'Bank account fetched successfully' },
  { code: 144, message: 'Bank account updated successfully' },
  { code: 145, message: 'Bank account deleted successfully' },
  { code: 146, message: 'Error creating bank account' },
  { code: 147, message: 'Error updating bank account' },
  { code: 148, message: 'Error deleting bank account' },
  { code: 149, message: 'Invalid input data' },
  { code: 150, message: 'Error fetching bank account' },

  // Bank Controller 160 till 189
  { code: 160, message: 'Bank created successfully' },
  { code: 161, message: 'Token not found' },
  { code: 162, message: 'Bank not found' },
  { code: 163, message: 'Bank fetched successfully' },
  { code: 164, message: 'Bank fetched successfully' },
  { code: 165, message: 'Bank updated successfully' },
  { code: 166, message: 'Bank deleted successfully' },
  { code: 167, message: 'Error creating bank' },
  { code: 168, message: 'Error fetching bank' },
  { code: 169, message: 'Error updating bank' },
  { code: 170, message: 'Error deleting bank' },
  { code: 171, message: 'Invalid input data' },

  // Cheque Book Controller 330 till 379
  { code: 330, message: 'Cheque book created successfully' },
  { code: 331, message: 'Token not found' },
  { code: 332, message: 'Cheque book not found' },
  { code: 333, message: 'Cheque book fetched successfully' },
  { code: 334, message: 'Record Fetched By Id' },
  { code: 335, message: 'Cheque book updated successfully' },
  { code: 336, message: 'Cheque book deleted successfully' },
  { code: 337, message: 'Error creating cheque book' },
  { code: 338, message: 'Error fetching cheque book' },
  { code: 339, message: 'Error updating cheque book' },
  { code: 340, message: 'Error deleting cheque book' },

  // Employee Controller 430 till 479
  { code: 430, message: 'Employee created successfully' },
  { code: 431, message: 'Token not found' },
  { code: 432, message: 'Employee not found' },
  { code: 433, message: 'Employee fetched successfully' },
  { code: 434, message: 'Record Fetched By Id' },
  { code: 435, message: 'Employee updated successfully' },
  { code: 436, message: 'Employee deleted successfully' },
  { code: 437, message: 'Error creating employee' },
  { code: 438, message: 'Error fetching employee' },
  { code: 439, message: 'Error updating employee' },
  { code: 440, message: 'Error deleting employee' },

  // System setting Controller 930 till 979
  { code: 930, message: 'System setting created successfully' },
  { code: 931, message: 'Token not found' },
  { code: 932, message: 'System setting not found' },
  { code: 933, message: 'System setting fetched successfully' },
  { code: 934, message: 'Record Fetched By Id' },
  { code: 935, message: 'System setting updated successfully' },
  { code: 936, message: 'System setting deleted successfully' },
  { code: 937, message: 'Error creating system setting' },
  { code: 938, message: 'Error fetching system setting' },
  { code: 939, message: 'Error updating system setting' },
  { code: 940, message: 'Error deleting system setting' },

  // Transactions Controller 1080 till 1129
  { code: 1080, message: 'Transactions created successfully' },
  { code: 1081, message: 'Token not found' },
  { code: 1082, message: 'Transactions not found' },
  { code: 1083, message: 'Transactions fetched successfully' },
  { code: 1084, message: 'Record Fetched By Id' },
  { code: 1085, message: 'Transactions updated successfully' },
  { code: 1086, message: 'Transactions deleted successfully' },
  { code: 1087, message: 'Error creating Transactions' },
  { code: 1088, message: 'Error fetching Transactions' },
  { code: 1089, message: 'Error updating Transactions' },
  { code: 1090, message: 'Error deleting Transactions' },

  // ActivityLogs Controller 1130 till 1179
  { code: 1130, message: 'ActivityLogs created successfully' },
  { code: 1131, message: 'Token not found' },
  { code: 1132, message: 'ActivityLogs not found' },
  { code: 1133, message: 'ActivityLogs fetched successfully' },
  { code: 1134, message: 'Record Fetched By Id' },
  { code: 1135, message: 'ActivityLogs updated successfully' },
  { code: 1136, message: 'ActivityLogs deleted successfully' },
  { code: 1137, message: 'Error creating ActivityLogs' },
  { code: 1138, message: 'Error fetching ActivityLogs' },
  { code: 1139, message: 'Error updating ActivityLogs' },
  { code: 1040, message: 'Error deleting ActivityLogs' },
];
